version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 378358292543.dkr.ecr.us-east-1.amazonaws.com/youtube
  post_build:
    commands:
      - docker push 378358292543.dkr.ecr.us-east-1.amazonaws.com/youtube
      - printf '[{"name":"MB0001-ECS-Container-01","imageUri":"%s"}]' 
        378358292543.dkr.ecr.us-east-1.amazonaws.com/youtube > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
